config/routes.rb
MyColleges::Application.routes.draw do

  resources :homes, only: [:index] do
    collection do
      get 'about'
    end
  end

  resources :schools
  resources :majors
  resources :school_follows
  resources :score_lines

  namespace :admin do
    resources :schools
    resources :majors
    resources :school_follows
    resources :score_lines
  end

  root :to => 'homes#index'

end

app/models/major.rb
# -*- encoding : utf-8 -*-

# == Schema Information
#
# Table name: majors
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  parent_id  :integer
#  code       :string(255)
#  college_type  :string(255)
#  eol_url    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Major < ActiveRecord::Base
  has_one :major_introduction
  attr_accessible :code, :college_type, :name, :parent_id, :eol_url

  ModelName = "专业"
  ColumnNames ={
    parent_id: "专业分类ID",
    name: "专业名称",
    code: "专业代号",
    college_type: "本科/专业"
  }

  def parent_name
    if self.parent_id.present?
      major = Major.where(id: parent_id).first
      major.name if major
    end
  end

  class << self

    def paginate_majors(options, page = 1, per_page = 10)
      conditions = []
      conditions << "parent_id != ''"
      conditions << "parent_id = #{options[:parent_id]}" if options[:parent_id].present?
      conditions << "college_type = '#{options[:college_type]}'" if options[:college_type].present?

      if options[:keyword].present?
        conditions << "name like '%#{options[:keyword]}%'"
      end

      paginate(conditions: conditions.join(" AND "),
               page: page,
               per_page: per_page,
               order: "id").all
    end

  end

end

app/models/sqlite/major.rb
# -*- encoding : utf-8 -*-

# == Schema Information
#
# Table name: majors
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  parent_id  :integer
#  code       :string(255)
#  college_type  :string(255)
#  eol_url    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Sqlite::Major < Sqlite::Base
  attr_accessible :code, :college_type, :name, :parent_id, :eol_url

  ModelName = "专业"
  ColumnNames ={
    parent_id: "专业分类ID",
    name: "专业名称",
    code: "专业代号",
    college_type: "本科/专业"
  }

end

app/controllers/admin/majors_controller.rb
# -*- encoding : utf-8 -*-

module Admin
  class MajorsController < BaseController
    before_filter :paginate_page, only: [:index]

    def index
      options = { parent_id: params[:parent_id],
                  college_type: params[:college_type],
                  keyword: params[:keyword] }
      @majors = Major.paginate_majors(options, @page)
    end

    def show
      @major = Major.find_by_id(params[:id])
    end

  end
end

app/controllers/majors_controller.rb
# -*- encoding : utf-8 -*-

class MajorsController < ApplicationController
  before_filter :paginate_page, only: [:index]

  def index
    options = { parent_id: params[:parent_id],
                college_type: params[:college_type],
                keyword: params[:keyword] }
    @majors = Major.paginate_majors(options, @page)
  end

  def show
    @major = Major.find_by_id(params[:id])
  end

end

app/helpers/majors_helper.rb
# -*- encoding : utf-8 -*-

module MajorsHelper

  def college_type_filters
    select_choices = [['本科','本科'],['专科','专科']]
    select_tag "college_type", options_for_select(select_choices, params[:college_type]),{prompt: "专业层次"}
  end

  def parent_major_filters
    majors = Major.where("id <= 30").order("id").all
    select_choices = majors.map { |p| [p.name,p.id.to_s]}
    select_tag "parent_id", options_for_select(select_choices, params[:parent_id]),{prompt: "专业分类"}
  end

  def major_icon(index)
    case index
    when 0
      "Chat@2x.png"
    when 1
      "Clipboard@2x.png"
    when 2
      "Map@2x.png"
    else
      "Watches@2x.png"
    end
  end

end

app/views/majors/_search_filters.html.erb
<br/>
<%= form_tag('/majors', :method => :get) do %>
  <p><%= college_type_filters %>&nbsp;&nbsp;<%= parent_major_filters %></p>
  <p><%= text_field_tag :keyword, params[:keyword], placeholder: "输入专业名称" %>&nbsp;&nbsp;<%= submit_tag '搜索', class: :btn %></p>
<% end %>

app/views/majors/index.html.erb
<%= render :partial => "search_filters" %>

<% if has_size?(@majors) %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>专业层次</th>
        <th>专业分类</th>
        <th>专业名称</th>
        <th>专业代号</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @majors.each do |major| %>
        <tr>
          <td><%= major.id %></td>
          <td><%= major.college_type %></td>
          <td><%= major.parent_name %></td>
          <td><%= major.name %></td>
          <td><%= major.code %></td>
          <td><%= link_to "查看", major_path(major.id), class: 'btn', target: "_blank" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= chinese_pagination @majors %>
<% end %>

app/views/majors/show.html.erb
<% if @major.present? %>
<fieldset>
  <legend>基本信息</legend>
  <table class="table table-hover">
    <tbody>
      <tr class="success">
        <td>专业层次</td>
        <td><%= @major.college_type %></td>
      </tr>
      <tr class="success">
        <td>专业分类</td>
        <td><%= @major.parent_name %></td>
      </tr>
      <tr class="error">
        <td>专业名称</td>
        <td><%= @major.name %></td>
      </tr>
      <tr class="error">
        <td>专业代号</td>
        <td><%= @major.code %></td>
      </tr>
    </tbody>
  </table>
</fieldset>


<fieldset>
    <legend>文字介绍</legend>
    <p>
    <% if @major.major_introduction %>
      <%= @major.major_introduction.content %>
    <% else %>
      无
    <% end %></p>
</fieldset>


<% end %>