config/routes.rb
MyColleges::Application.routes.draw do

  resources :homes, only: [:index] do
    collection do
      get 'about'
    end
  end

  resources :schools
  resources :majors
  resources :school_follows
  resources :score_lines

  namespace :admin do
    resources :schools
    resources :majors
    resources :school_follows
    resources :score_lines
  end

  root :to => 'homes#index'

end

app/models/extras/school_types.rb
# -*- encoding : utf-8 -*-

module Extras
  module SchoolTypes

    PROFESSIONAL_TYPES = {
      "integrated" => {
        title: "综合",
        code: "integrated",
        number: 580
      },
      "engineering" => {
        title: "工科",
        code: "engineering",
        number: 767
      },
      "teacher" => {
        title: "师范",
        code: "teacher",
        number: 219
      },
      "medicine" => {
        title: "医药",
        code: "medicine",
        number: 154
      },
      "agriculture" => {
        title: "农业",
        code: "agriculture",
        number: 87
      },
      "finance" => {
        title: "财经",
        code: "finance",
        number: 202
      },
      "politics" => {
        title: "政法",
        code: "politics",
        number: 70
      },
      "language" => {
        title: "语言",
        code: "language",
        number: 44
      },
      "forestry" => {
        title: "林业",
        code: "forestry",
        number: 18
      },
      "arts" => {
        title: "艺术",
        code: "arts",
        number: 76
      },
      "sports" => {
        title: "体育",
        code: "sports",
        number: 30
      },
      "ethnic" => {
        title: "民族",
        code: "ethnic",
        number: 18
      },
      "military" => {
        title: "军事",
        code: "military",
        number: 13
      }
    }

    def professional_type_choices
      sorted_types = PROFESSIONAL_TYPES.sort_by {|key, type| type[:number]}.reverse
      sorted_types.map {|type| [type[1][:title], type[1][:code]]}
    end

    def professional_type_name(code)
      if PROFESSIONAL_TYPES.has_key?(code)
        PROFESSIONAL_TYPES[code][:title]
      end
    end

    def self.included(base)
      base.extend(ClassMethods)
    end

    module ClassMethods

      def professional_type_name(code)
        if PROFESSIONAL_TYPES.has_key?(code)
          PROFESSIONAL_TYPES[code][:title]
        end
      end

    end

  end
end

app/models/school.rb
# -*- encoding : utf-8 -*-

# == Schema Information
#
# Table name: schools
#
#  id          :integer          not null, primary key
#  detail_type :string(255)      not null
#  detail_id   :integer          not null
#  country_id  :integer
#  province_id :integer
#  city_id     :integer
#  nick_name   :string(255)
#  real_name   :string(255)
#  web_site    :string(255)
#  found_year  :string(255)
#  ifeng_code  :string(255)
#  address     :string(255)
#  telephone   :string(255)
#  sina_code   :string(255)
#  latitude     :string(255)
#  longitude   :string(255)
#  zipcode   :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class School < ActiveRecord::Base

  include Extras::SchoolTypes

  belongs_to :detail, polymorphic: true
  belongs_to :country
  belongs_to :province
  belongs_to :city

  has_one :school_introduction
  has_one :school_avatar, class_name: "SchoolPhoto", conditions: ["is_avatar = ?", true]
  has_many :school_photos
  has_many :school_follows

  attr_accessible :country_id, :province_id, :city_id,
                  :nick_name, :real_name, :web_site,
                  :found_year, :ifeng_code, :address,
                  :telephone, :sina_code, :latitude,
                  :longitude, :zipcode

  validates_presence_of :nick_name, :detail_type, :detail_id

  ModelName = "学校"
  ColumnNames ={
    country_id: "所在国家",
    province_id: "所在省份",
    city_id: "所在城市",
    nick_name: "别名",
    real_name: "真名",
    web_site: "网址",
    found_year: "创建年份",
    address: "地址",
    telephone: "联系电话",
    latitude: "纬度",
    longitude: "经度",
    zipcode: "邮政编码"
  }

  def build_content(content)
    SchoolIntroduction.build_intro(self.id, content)
  end

  def is_domestic?
    detail_type.present? && detail_type == 'Domestic'
  end

  def school_type_name
    self.is_domestic? ? "国内" : "国外"
  end

  ['country', 'province', 'city'].each do |field|
    define_method("#{field}_name") do
      field_value = self.send("#{field}_id")
      if field_value.present?
        self.send("#{field}").real_name
      else
        "无"
      end
    end
  end

  def full_content
    if self.school_introduction
      self.school_introduction.full_content
    else
      "信息暂无"
    end
  end

  def refresh_address(params)
    self.update_attributes(params)
  end

  class << self

    def paginate_schools(options, page = 1, per_page = 10)
      conditions = []
      joins = "join domestics on schools.detail_id = domestics.id"

      if options[:province].present?
        conditions << "schools.province_id = #{options[:province]}"
      end

      if options[:professional_type].present?
        professional_type = professional_type_name(options[:professional_type])
        if professional_type
          conditions << "domestics.college_type = '#{professional_type}'"
        end
      end

      if options[:keyword].present?
        conditions << "schools.real_name like '%#{options[:keyword]}%'"
      end

      paginate(select: "schools.id,schools.province_id,schools.real_name",
               conditions: conditions.join(" AND "),
               joins: joins,
               page: page,
               per_page: per_page,
               order: "id").all
    end

    def build_sina_domestic(params)
      domestic = Domestic.build!(params)
      if domestic
        school = self.new(country_id: params[:country_id],
                          province_id: params[:province_id],
                          nick_name: params[:nick_name],
                          real_name: params[:nick_name],
                          web_site: params[:web_site],
                          address: params[:address],
                          telephone: params[:telephone],
                          sina_code: params[:sina_code])
        school.detail = domestic

        if school.valid? && school.save!
          #SchoolIntroduction.build_intro(school.id, params[:content])
          school
        end
      end
    end

    def build_ifeng_domestic(params)
      province = Province.get_by_name(params[:province_name])
      unless province
        Rails.logger.info "province not found name (#{params[:province_name]})"
        return
      end

      domestic = Domestic.build!(params)
      if domestic
        school = self.new(country_id: province.country_id,
                          province_id: province.id,
                          nick_name: params[:nick_name],
                          real_name: params[:nick_name],
                          web_site: params[:web_site],
                          ifeng_code: params[:ifeng_code])
        school.detail = domestic

        if school.valid? && school.save!
          #SchoolIntroduction.build_intro(school.id, params[:content])
          school
        end
      end
    end

  end

end

app/models/sqlite/school.rb
# -*- encoding : utf-8 -*-

# == Schema Information
#
# Table name: schools
#
#  id          :integer          not null, primary key
#  detail_type :string(255)      not null
#  detail_id   :integer          not null
#  country_id  :integer
#  province_id :integer
#  city_id     :integer
#  nick_name   :string(255)
#  real_name   :string(255)
#  web_site    :string(255)
#  found_year  :string(255)
#  ifeng_code  :string(255)
#  address     :string(255)
#  telephone   :string(255)
#  sina_code   :string(255)
#  latitude     :string(255)
#  longitude   :string(255)
#  zipcode   :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sqlite::School < Sqlite::Base
  attr_accessible :country_id, :province_id, :city_id,
                  :nick_name, :real_name, :web_site,
                  :found_year, :ifeng_code, :address,
                  :telephone, :sina_code, :latitude,
                  :longitude, :zipcode, :college_type, :is_211, :is_985, :affiliate,
                  :is_edu_affiliate, :has_bachelor, :is_independent,
                  :is_civilian_run, :key_disciplines, :master_num,
                  :phd_num, :academician_num

  ModelName = "学校"
  ColumnNames ={
    country_id: "所在国家",
    province_id: "所在省份",
    city_id: "所在城市",
    nick_name: "别名",
    real_name: "真名",
    web_site: "网址",
    found_year: "创建年份",
    address: "地址",
    telephone: "联系电话",
    latitude: "纬度",
    longitude: "经度",
    zipcode: "邮政编码"
  }

end

app/controllers/admin/schools_controller.rb
# -*- encoding : utf-8 -*-

module Admin
  class SchoolsController < BaseController
    before_filter :paginate_page, only: [:index]

    def index
      options = { province: params[:province],
                  professional_type: params[:professional_type],
                  keyword: params[:keyword] }
      @schools = School.paginate_schools(options, @page)
    end

    def show
      @school = School.find_by_id(params[:id])
    end

  end
end

app/controllers/schools_controller.rb
# -*- encoding : utf-8 -*-

class SchoolsController < ApplicationController
  before_filter :paginate_page, only: [:index]

  def index
    options = { province: params[:province],
                professional_type: params[:professional_type],
                keyword: params[:keyword] }
    @schools = School.paginate_schools(options, @page)
  end

  def show
    @school = School.find_by_id(params[:id])
  end

end

app/helpers/schools_helper.rb
# -*- encoding : utf-8 -*-

module SchoolsHelper

  def province_filters
    provinces = Province.order("id").all
    select_choices = provinces.map { |p| [p.real_name,p.id.to_s]}
    select_tag "province", options_for_select(select_choices, params[:province]),{prompt: "院校省份"}
  end

  def professional_type_filters
    select_choices = professional_type_choices
    select_tag "professional_type", options_for_select(select_choices, params[:professional_type]),{prompt: "院校类型"}
  end

end

app/views/schools/_search_filters.html.erb
<br/>
<%= form_tag('/schools', :method => :get) do %>
  <p><%= province_filters %>&nbsp;&nbsp;<%= professional_type_filters %></p>
  <p><%= text_field_tag :keyword, params[:keyword], placeholder: "输入院校名称" %>&nbsp;&nbsp;<%= submit_tag '搜索', class: :btn %></p>

<% end %>

app/views/schools/index.html.erb
<%= render :partial => "search_filters" %>

<% if has_size?(@schools) %>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>所在省份</th>
        <th>学校图片</th>
        <th>学校名称</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @schools.each do |school| %>
        <tr>
          <td><%= school.id %></td>
          <td><%= school.province_name %></td>
          <td>
            <% if(avatar = school.school_avatar) %>
              <%= image_tag avatar.photo_url, style: "width:60px;height:60px;" %>
            <% else %>
              无图
            <% end %>
          </td>
          <td><%= school.real_name %></td>
          <td><%= link_to "查看", school_path(school.id), class: 'btn', target: "_blank" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= chinese_pagination @schools %>
<% end %>

app/views/schools/show.html.erb
<% if @school.present? %>
<fieldset>
    <legend>基本信息</legend>
    <%= render :partial => "/common/school_follow_panel", :locals => { :school => @school } %>
    <table class="table table-hover">
      <tbody>
        <% if(avatar = @school.school_avatar) %>
          <tr class="success">
            <td>学校图片</td>
            <td><%= image_tag avatar.photo_url %></td>
          </tr>
        <% end %>
        <tr class="success">
          <td>学校名称</td>
          <td><%= @school.real_name %></td>
        </tr>
        <tr class="success">
          <td>学校网址</td>
          <td><%= link_to @school.web_site, @school.web_site %></td>
        </tr>
        <tr class="error">
          <td>类型</td>
          <td><%= @school.detail.college_type %></td>
        </tr>
        <tr class="error">
          <td>是否211</td>
          <td><%= @school.detail.is_211 %></td>
        </tr>
        <tr class="error">
          <td>是否985</td>
          <td><%= @school.detail.is_985 %></td>
        </tr>
        <tr class="warning">
          <td>院校隶属</td>
          <td><%= @school.detail.affiliate %></td>
        </tr>
        <tr class="warning">
          <td>教育部直属院校</td>
          <td><%= @school.detail.is_edu_affiliate %></td>
        </tr>
        <tr class="warning">
          <td>设立研究生院</td>
          <td><%= @school.detail.has_bachelor %></td>
        </tr>
        <tr class="warning">
          <td>独立学院</td>
          <td><%= @school.detail.is_independent %></td>
        </tr>
        <tr class="warning">
          <td>民办院校</td>
          <td><%= @school.detail.is_civilian_run %></td>
        </tr>
        <tr class="info">
          <td>国家重点学科</td>
          <td><%= @school.detail.key_disciplines %></td>
        </tr>
        <tr class="success">
          <td>院士</td>
          <td><%= @school.detail.master_num %></td>
        </tr>
        <tr class="error">
          <td>博士点</td>
          <td><%= @school.detail.phd_num %></td>
        </tr>
        <tr class="warning">
          <td>硕士点</td>
          <td><%= @school.detail.academician_num %></td>
        </tr>
      </tbody>
    </table>
</fieldset>

<fieldset>
    <legend>地理位置</legend>
  <table class="table table-hover">
      <tbody>
        <tr class="success">
          <td>所在省份</td>
          <td><%= @school.province_name %></td>
        </tr>
        <tr class="success">
          <td>所在城市</td>
          <td><%= @school.city_name %></td>
        </tr>
        <tr class="success">
          <td>学校地址</td>
          <td><%= @school.address %></td>
        </tr>
        <tr class="error">
          <td>联系电话</td>
          <td><%= @school.telephone %></td>
        </tr>
        <% if @school.latitude.present? && @school.longitude.present? %>
          <tr class="success">
            <td>地图位置</td>
            <td><img src="http://maps.google.com/maps/api/staticmap?center=<%=@school.latitude%>,<%=@school.longitude%>&zoom=12&size=300x150&maptype=roadmap&markers=color:blue|label:P|<%=@school.latitude%>,<%=@school.longitude%>&sensor=false" /></td>
          </tr>
        <% end %>
      </tbody>
  </table>
</fieldset>


<fieldset>
    <legend>文字介绍</legend>
    <p><%= @school.full_content %></p>
</fieldset>

<% end %>